import mbook from '../../../assets/mbook.jpg'
import ebook from '../../../assets/ebook.jpg'
export const books = [
  {
    id: 1,
    img: mbook,
    type: "myanmar",
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 2,
    img: mbook,
    type: "myanmar",
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MNovel",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 3,
    type: "myanmar",
    img: mbook,
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 4,
    type: "myanmar",
    img: mbook,
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MTechnology",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 5,
    img: mbook,
    type: "myanmar",
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MReligious",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 6,
    img: mbook,
    type: "myanmar",
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 7,
    img: mbook,
    type: "myanmar",
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 8,
    img: mbook,
    type: "myanmar",
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 9,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "ENovel",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 10,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "EStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 11,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "EStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 12,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "EStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 13,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "ETechnology",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 14,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "EStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 15,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "ETechnology",
    quantity: 1,
    page: 332,
    price: 24.22,
  },{
    id: 16,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "EStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 17,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "ETechnology",
    quantity: 1,
    page: 332,
    price: 24.22,
  },{
    id: 18,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "EStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 19,
    img: ebook,
    type: "english",
    title: "Real Life",
    author: "Brandon Taylor",
    bookType: "ETechnology",
    quantity: 1,
    page: 332,
    price: 24.22,
  },{
    id: 20,
    img: mbook,
    type: "myanmar",
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MStory",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
  {
    id: 21,
    img: mbook,
    type: "myanmar",
    title: "ဂရုမစိုက်ခြင်း အနုပညာ",
    author: "ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်",
    bookType: "MTechnology",
    quantity: 1,
    page: 332,
    price: 24.22,
  },
];

